language: c++


install:
    - sudo apt-get update -qq
    - sudo apt-get install
        devscripts
        libgmp-dev
        libmpfr-dev
        libmpc-dev
        texinfo
        bison

before_script:
    - cd packaging/deb

script:
    - make prepare-packages
    - cd adtools-sdk && debuild -i -us -uc -b && cd ..
    - cd adtools-binutils && debuild -i -us -uc -b && cd ..
