sudo: required
dist: trusty
language: c++
install:
- sudo apt-get update -qq
- sudo apt-get install -y debhelper devscripts libgmp-dev libmpfr-dev libmpc-dev texinfo bison
  flex lhasa
before_script:
- cd packaging/deb
script:
- make prepare-packages
- cd adtools-sdk && debuild -i -us -uc -b && cd ..
- cd adtools-binutils && debuild -i -us -uc -b && cd ..
- sudo dpkg -i *.deb
- cd adtools-gcc
- travis_wait 30 "sh -c debuild -i -us -uc -b >/tmp/build.out"
- cd ..
- sudo dpkg -i *gcc*.deb
- mkdir artifacts
- mv *.deb artifacts
- cd artifacts
- dpkg-scanpackages ./ /dev/null | gzip >Packages.gz
# Native compile, take adventage of previous steps
- cd ../../..
- mv packaging/deb/adtools-binutils/patched binutils/repo
- mv packaging/deb/adtools-gcc/patched gcc/repo
- unset CC
- make -C native-build CROSS_IS_PRESENT=1
env:
  global:
  - secure: mlPpfQG9RuayWWXLt1tdEI4nb9ElObenj1QDfJ8qGxEqGleout8RE9cIxArB3WJ8jih/9lM3mkUm0y3cMMsf+SGRkfkWLO+YmVHqMslC0dwd3CqPMFjYPSJh7qsxaJC3b0RrZXujlXkwgDP16Yy/+h9RqAQwuTc3AtWepcLEZp0=
  - secure: viZg+Dmh8k1acvKYBf5yzDdTClekE5fqx84CttWZnljQlwVWbfJEqjSvWoyAvI07UosY69y3vJ5VKjIViDcz1N36LjcV+sxnWIfSwfTa6bCWeYS03cERlKQB6QJPR+RR/UFhloJy5XQyaLzC1TdVQTH4A01OV49uN8uUKjh7hyk=
after_success:
 - pwd
 - ls
 - ./bin/adtdeploy
after_failure:
 - pwd
 - cat /tmp/build.out
